// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatTheFlux.Api.Data;

#nullable disable

namespace WhatTheFlux.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327075138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("WhatTheFlux.Api.Models.CriterionCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriterionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DayEntryId", "CriterionId")
                        .IsUnique();

                    b.ToTable("CriterionCounts");
                });

            modelBuilder.Entity("WhatTheFlux.Api.Models.DayEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId", "DayNumber")
                        .IsUnique();

                    b.ToTable("DayEntries");
                });

            modelBuilder.Entity("WhatTheFlux.Api.Models.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("WhatTheFlux.Api.Models.CriterionCount", b =>
                {
                    b.HasOne("WhatTheFlux.Api.Models.DayEntry", "DayEntry")
                        .WithMany("Counts")
                        .HasForeignKey("DayEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayEntry");
                });

            modelBuilder.Entity("WhatTheFlux.Api.Models.DayEntry", b =>
                {
                    b.HasOne("WhatTheFlux.Api.Models.Period", "Period")
                        .WithMany("Days")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("WhatTheFlux.Api.Models.DayEntry", b =>
                {
                    b.Navigation("Counts");
                });

            modelBuilder.Entity("WhatTheFlux.Api.Models.Period", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
